- name: redmine_wiki_extensions
  become: yes
  git:
    repo=https://github.com/haru/redmine_wiki_extensions.git
    dest={{ redmine_dir }}/plugins/redmine_wiki_extensions
    version=refs/tags/0.7.0
