- name: redmine_wiki_extensions ソースコードをダウンロード
  become: yes
  get_url:
    url: https://bitbucket.org/haru_iida/redmine_wiki_extensions/downloads/redmine_wiki_extensions-0.7.0.zip
    dest: /tmp

- name: redmine_wiki_extensions ソースコードを解凍
  become: yes
  command:
    unzip -o -d {{ redmine_dir }}/plugins /tmp/redmine_wiki_extensions-0.7.0.zip
 
- name: Run rake
  become: yes
  command:
    bundle exec rake redmine:plugins:migrate
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: Restart redmine
  become: yes
  service: name=httpd state=restarted
