- name: redmine_wiki_extensions_download
  become: yes
  get_url:
    url: https://github.com/haru/redmine_wiki_extensions/archive/0.7.0.zip
    dest: /tmp

- name: redmine_wiki_extensions_extract
  become: yes
  unarchive: src=/tmp/redmine_wiki_extensions-0.7.0.zip dest={{ redmine_dir }}/plugins

