- name: farend_basicテーマのダウンロード
  become: yes
  git:
    repo=https://github.com/farend/redmine_theme_farend_basic.git
    dest={{ redmine_dir }}/public/themes/farend_basic

- name: flat_theme のダウンロード
  become: yes
  git:
    repo=https://github.com/ssaito/redmine-theme-flat.git
    dest={{ redmine_dir }}/public/themes/redmine_flat

- name: theme_gitmike のダウンロード
  become: yes
  git:
    repo=https://github.com/makotokw/redmine-theme-gitmike.git
    dest={{ redmine_dir }}/public/themes/gitmike

- name: theme_purplemine2 のダウンロード
  become: yes
  git:
    repo=https://github.com/taqueci/PurpleMine2.git
    dest={{ redmine_dir }}/public/themes/PurpleMine2

- name: テーマをredmine_flat に切り替え
  become: yes
  command:
    bundle exec rails r 'Setting["ui_theme"]="redmine_flat"'
    chdir={{ redmine_dir }}
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
  when:
    result_database_yml|changed
